import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Requested core colors
        "accent-primary": "#FF6B00",
        "bg-core": "#FFFFFF",
        "surface-core": "#F8F9FB",
        "border-core": "#E5E7EB",
        "text-core": "#111827",
        "text-secondary-core": "#6B7280",
        "success-core": "#22C55E",
        "warning-core": "#F59E0B",
        "error-core": "#EF4444",

        // Stitch Palette Map
        "primary-fixed-dim": "#ffb693",
        "primary-fixed": "#ffdbcc",
        "surface-container-lowest": "#ffffff",
        "surface": "#fff8f6",
        "on-tertiary-container": "#003357",
        "surface-container-high": "#fee3d8",
        "secondary-fixed": "#dce2f7",
        "tertiary-container": "#059eff",
        "on-secondary-fixed": "#141b2b",
        "secondary": "#575e70",
        "background": "#fff8f6",
        "on-surface": "#261812",
        "on-tertiary-fixed-variant": "#00497b",
        "error-container": "#ffdad6",
        "surface-dim": "#efd5ca",
        "primary-container": "#ff6b00",
        "tertiary-fixed-dim": "#9ccaff",
        "on-primary": "#ffffff",
        "outline": "#8e7164",
        "on-background": "#261812",
        "surface-variant": "#f8ddd2",
        "primary": "#a04100",
        "on-secondary-container": "#5c6274",
        "surface-container": "#ffeae1",
        "surface-bright": "#fff8f6",
        "on-secondary-fixed-variant": "#404758",
        "inverse-primary": "#ffb693",
        "on-primary-container": "#572000",
        "surface-tint": "#a04100",
        "on-primary-fixed": "#351000",
        "inverse-surface": "#3d2d26",
        "inverse-on-surface": "#ffede6",
        "tertiary": "#0062a1",
        "secondary-container": "#d9dff5",
        "surface-container-highest": "#f8ddd2",
        "outline-variant": "#e2bfb0",
        "surface-container-low": "#fff1eb",
        "on-primary-fixed-variant": "#7a3000",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#001d35",
        "secondary-fixed-dim": "#c0c6db",
        "tertiary-fixed": "#d0e4ff",
        "on-surface-variant": "#5a4136",
        "error": "#ba1a1a",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "12px",
        "2xl": "16px",
        "3xl": "24px",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "lg": "48px",
        "sm": "12px",
        "base": "8px",
        "gutter": "24px",
        "xl": "80px",
        "xs": "4px",
        "container-max": "1280px",
        "md": "24px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "800" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-lg": ["20px", { lineHeight: "1.8", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
};
export default config;
